use crate::compiler::regalloc::linear_scan::AllocatedProgram;

pub fn emit(prog: AllocatedProgram) -> String {
    let mut asm = String::new();
    asm.push_str("; ====================================================================\n");
    asm.push_str(&format!("; Generated by Impulse Compiler Core (.impscm)\n"));
    asm.push_str("; Target: ImpulseVM impOps Specification v0.9.0\n");
    asm.push_str("; ====================================================================\n\n");
    asm.push_str(".relation \"DIRECT_MEMBER\" = 0\n");
    asm.push_str(".relation \"GROUP_PARENT\" = 1\n");
    asm.push_str(".relation \"DOC_VIEWER\" = 2\n");
    asm.push_str(".relation \"FOLLOWS\" = 3\n");
    asm.push_str(".relation \"DEPENDS_ON\" = 4\n\n");
    asm.push_str(".text\n");
    asm.push_str(&format!("{}:\n", prog.function_name));
    asm.push_str(&format!("    OP_ENTER_FRAME              R{}\n", prog.frame_size));

    for inst in &prog.instructions {
        if inst.opcode == "OP_LEAVE_FRAME" || inst.opcode == "OP_RET" {
            asm.push_str(&format!("    {:30}\n", inst.opcode));
            continue;
        }

        let mut line = format!("    {:30}", inst.opcode);
        let mut operands = Vec::new();
        if let Some(ref dst) = inst.dst {
            operands.push(dst.clone());
        }
        operands.extend(inst.args.clone());

        if !operands.is_empty() {
            line.push_str(&operands.join(", "));
        }
        asm.push_str(&line);
        asm.push('\n');
    }

    asm
}
